### ISSUE TITLE
Riot inside Revolt w/Flatpak does not notice when a network connection is back

### ISSUE THREAD

**Issue by aperezdc** [aperezdc/revolt#16]
## Steps to reproduce

1. Run Revolt **with Flatpak**.
2. Suspend the computer.
3. Resume the computer.

## Expected outcome

Riot notices that the network connection is back, and restarts normal operation by itself.

## Actual outcome

Riot keeps showing the message “Connectivity to the server has been lost” regardless of how long one waits after resuming the computer.

## Additional information

Running Riot inside GNOME Web (a.k.a. Epiphany) works and Riot notices that the connection is back. Could it be that Epiphany is doing something behind the scene with NetworkManager?

**Comment by Half-Shot** [comment]
Hmm, mine actually worked fine during suspend and resume :|

**Comment by aperezdc** [comment]
Maybe this is something that has to do with my particular setup. I'll try to see if I can reproduce this consistently while looking at the `console.log` output.

**Comment by aperezdc** [comment]
Okay, this has happened again to me today...

@Half-Shot: You said that Riot inside Revolt noticed the connection coming back after suspending and resuming the computer. IIRC you are _not_ running the application with Flatpak, could you confirm that? (Because I am using the Flatpak, and I suspect its sandbox may have something to do with the issue.)

**Comment by Half-Shot** [comment]
Can confirm that I am not using flatpack

On 15 November 2016 19:52:50 GMT+00:00, Adrian Perez <notifications@github.com> wrote:
>Okay, this has happened again to me today...
>
>@Half-Shot: You said that Riot inside Revolt noticed the connection
>coming back after suspending and resuming the computer. IIRC you are
>_not_ running the application with Flatpak, could you confirm that?
>(Because I am using the Flatpak, and I suspect its sandbox may have
>something to do with the issue.)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/aperezdc/revolt/issues/16#issuecomment-260748077

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jaragunde** [comment]
I can reproduce it just by changing networks (e.g. undock my laptop and change from ethernet to wifi). It can also be reproduced by stopping the network connection until the "connectivity lost" message shows up, then reconnect.

**Comment by aperezdc** [comment]
My suspicion is that WebKitGTK+ uses NetworkManager when available (D-Bus) to detect the current connectivity, or something else which is not available from inside the Flatpak sandbox. It shouldn't be too hard to figure out :wink:

**Comment by aperezdc** [comment]
I cannot reproduce this anymore. Since the last comments in this issue there has been some minor updates of the GNOME runtime, plus new releases of Flatpak, and the XDG portal helpers — things may as well be fixed now.

If somebody experiences this issue again, please reopen.
