### ISSUE TITLE
access to JavaScript console

### ISSUE THREAD

**Issue by uhoreg** [aperezdc/revolt#20]
Can you add some way to access the JavaScript console, for debugging purposes?  Thanks

**Comment by aperezdc** [comment]
This shouldn't be too difficult, because the whole inspector (including the JavaScript console) is implemented in WebKitGTK+, thanks for the suggestion!

**Comment by clopez** [comment]
You only have to enable the [developer-extras](https://webkitgtk.org/reference/webkitgtk/stable/WebKitWebSettings.html#WebKitWebSettings--enable-developer-extras) setting for the webview, and then you should be able execute the inspector via the right click contextual menu on the webview

**Comment by aperezdc** [comment]
@clopez Oh, I had forgotten about that one, cool!

**Comment by aperezdc** [comment]
@uhoreg There is not a “Developer Tools” toggle button in the preferences dialog which allows accessing the WebKitGTK+ inspector. Once enabled, you can right-click anywhere on the embedded webview and choose “Inspect element” as @clopez mentioned.
