### ISSUE TITLE
Intermittent error: Portal operation not allowed 

### ISSUE THREAD

**Issue by aperezdc** [aperezdc/revolt#30]
Sporadically, when launching the Revolt Flatpak the following message is shown in the web view:

```
GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Portal operation not allowed:
Unable to open /proc/15888/root
```

This happens more often when running a [Budgie](https://github.com/budgie-desktop/budgie-desktop) session.

Screenshot:

![screenshot from 2016-12-08 16-55-05](https://cloud.githubusercontent.com/assets/723451/21014536/20c595c2-bd67-11e6-8b79-e1d9a3bcee2e.png)

**Comment by aperezdc** [comment]
I have discovered that killing the following processes, the application works normally on the next launch:

```
  684 ?        Ssl    0:00 /usr/lib/flatpak/xdg-permission-store
 9658 ?        Ssl    0:00 /usr/lib/flatpak/xdg-permission-store
25167 ?        Ssl    0:00 /usr/lib/flatpak/xdg-document-portal
26414 ?        Sl     0:00 /usr/lib/xdg-desktop-portal
26420 ?        Sl     0:00 /usr/lib/xdg-desktop-portal-gtk
```

**Comment by aperezdc** [comment]
In particular, it's only needed to kill `xdg-desktop-portal` to get things working again. This seems quite odd and I am starting to seriously think it may be an upstream bug.

**Comment by aperezdc** [comment]
This is still happening after upgrading to version 0.5 of `xdg-desktop-portal` and `xdg-desktop-portal-gtk` :disappointed:

**Comment by tanty** [comment]
Same experience here. Debian Testing with xdg-desktop-portal 0.4-1 and xdg-desktop-portal-gtk 0.3-1

> I have discovered that killing the following processes, the application works normally on the next launch:

Not in my case. Right now I don't have a solution for this. I cannot use Revolt any more...

**Comment by aperezdc** [comment]
I have not been experiencing this issue lately, currently I am using:

```
% pacman -Qi xdg-desktop-portal | grep '^Version'
Version         : 0.5-3
% pacman -Qi xdg-desktop-portal-gtk | grep '^Version'
Version         : 0.5-3
% 
```

**Comment by aperezdc** [comment]
This seems to be gone for good with the latest release of Flatpak and the portals. Closing.

**Comment by thiblahute** [comment]
fwiw I got the same issue here with xdg-desktop-portal 1.4.2 in our WebKit flatpak dev env :|
