### ISSUE TITLE
Flatpak: Cannot open links after updating to xdg-desktop-portal 0.4

### ISSUE THREAD

**Issue by aperezdc** [aperezdc/revolt#31]
I am not 100% sure about this, but it started happening after the update, so most likely that is the culprit. We need to check whether:

* Revolt might need permission to talk to some (new?) portal endpoint(s) over D-Bus, or
* This is a legitimate upstream bug and should be reported escalated to [xdg-desktop-portal](https://github.com/flatpak/xdg-desktop-portal).

**Comment by aperezdc** [comment]
Still happening with `xdg-desktop-portal` 0.5 :disappointed:

**Comment by tanty** [comment]
$ dpkg -l | grep xdg                                                                                                                                                                                 
...
ii  xdg-desktop-portal                                               0.5-1                                amd64        desktop integration portal for Flatpak
ii  xdg-desktop-portal-gtk                                           0.5-1                                amd64        GTK/GNOME portal backend for xdg-desktop-portal
...

Still happening ...

**Comment by aperezdc** [comment]
Probably what we need here is to use [gtk.show_uri_on_window()](https://developer.gnome.org/gtk3/stable/gtk3-Filesystem-utilities.html#gtk-show-uri-on-window) instead of `gtk.show_uri()`. I just stumbled upon it while skimming over the GNOME 3.24 release notes :sweat_smile:

**Comment by aperezdc** [comment]
The commit that I have just pushed fixed the issue for me.

@tanty: Could you confirm? I have pushed a new build to the Flatpak repository with this fix included.

**Comment by aperezdc** [comment]
After chatting with @tanty, it turns out his comment was about issue #30 instead. I'll close this for now, if the issue shows again, we can always reopen it later.
