### ISSUE TITLE
Use the light adwaita theme instead of the dark one

### ISSUE THREAD

**Issue by allanday** [aperezdc/revolt#37]
The dark theme variant is really meant for media applications, like video or photos, where the chrome shouldn't compete with the content. This isn't the case for a messaging app. The dark theme seems particularly inappropriate for Riot - it is so light that the dark theme looks out of place.

**Comment by aperezdc** [comment]
This is solved as of commit a333eb4f63acc5c21187ddafe10bb78f3a3c4d3d, though as per discussion in [#gnome:matrix.org](https://matrix.to/#/#gnome:matrix.org) it would be nice if the chosen GTK+ theme variant would follow Riot's theme choice. I have opened #38 to track implementing that.
