### ISSUE TITLE
Be more selective regarding when to notify

### ISSUE THREAD

**Issue by afranke** [aperezdc/revolt#40]
It seems I get a notification for every message sent to a room I joined. This can quickly get noisy and I probably only want to know about mentions.

**Comment by aperezdc** [comment]
@afranke: You can choose which events get notified by tweaking the notification settings using Riot's settings panel. Also, probably we would also want Revolt to swallow notification sounds when it is the focused application, and the needed code bits for that would be closely related to #39, so I think first we have to tackle that one.

**Comment by afranke** [comment]
Looking at Riot's settings panel, I don't see anything regarding notifications. I have display name, account creation, avatar, URL preview, rich text editor and a bunch of information.

**Comment by aperezdc** [comment]
@afranke: Here I see the following in the settings... Maybe if you're using Riot as a guest some things are not enabled.

![riot-notif-settings](https://cloud.githubusercontent.com/assets/723451/22248861/45adcb46-e249-11e6-9759-ae39bce35ef4.png)

**Comment by afranke** [comment]
Indeed, probably because I'm using it as a guest.
