### ISSUE TITLE
Right click on a link, copy URL doesn't work

### ISSUE THREAD

**Issue by afranke** [aperezdc/revolt#44]
When a link appears, try right clicking on it and copy link address. Then try pasting it anywhere *outside* of the app, it doesn't paste anything. It works if you paste it in the app though.

**Comment by aperezdc** [comment]
@afranke: That is working for me. Are you somehow using a Wayland session? It is a known issue that the X11 (via XWayland) and Wayland clipboard have some interop issues. For example copying from an application using Wayland and then trying to paste in a X11 application will kind of hang for a bit, and if you go back to the Wayland application and press `Ctrl+C` again then the paste finally succeeds in the X11 one.

**Comment by aperezdc** [comment]
@afranke: The bug I think you may be hitting is [#776638 - Clipboard broken Wayland](https://bugzilla.gnome.org/show_bug.cgi?id=776638).

**Comment by afranke** [comment]
I am indeed on Wayland. So Revolt is a X11 app? That's sad. Feel free to close this one if you think the upstream report is enough.

**Comment by aperezdc** [comment]
@afranke: Revolt itself runs just fine on Wayland — it will use whichever backend GDK picks, which is Wayland if you are using a Wayland session. But the other application where you are trying to paste could be running on X11. Or you have something funny going on in your system and some applications are using X11 (XWayland) when they should not.

**Comment by afranke** [comment]
Ah, so indeed it works between Revolt and gedit. Firefox must be the one still not using Wayland then! Thanks.
