### ISSUE TITLE
Notifications don't have icons

### ISSUE THREAD

**Issue by allanday** [aperezdc/revolt#47]
Each notification should have an icon with it. In GNOME 3.22 a full colour application icon is used, although in 3.24 we are switching to use symbolics.

In both cases, notifications from Revolt don't have an icon, which doesn't look so great.

**Comment by aperezdc** [comment]
Initially I didn't add the application icon because I was hoping of finding some way of getting the avatar of the room/user who caused the notification, but never got round to it. There's already a symbolic icon for Revolt, it should be a piece of cake to pass it to the `GNotification`.

**Comment by aperezdc** [comment]
It turns out that `notif.set_icon()` was being called, but the name of the icon being loaded was one that doesn't exist anymore. I fixed that and also changed over to use the symbolic icon.
