### ISSUE TITLE
Hidden xdg-desktop-portal-gtk window

### ISSUE THREAD

**Issue by jaragunde** [aperezdc/revolt#48]
Not sure if I should be reporting this here, maybe it's a flatpak problem. Here it goes anyway ;-)

When you click on a link inside Revolt, an xdg-desktop-portal-gtk window is opened to let you select which application would take care of the link (among the several browsers you may have).

In my system, it works normally *only the first time* I click on a link, but the second and successive times the portal window will open in background, and I have to press alt+tab to reach it.

Using:
* Fedora 24
* GNOME 3.20.2
* Flatpak 0.8.4

**Comment by aperezdc** [comment]
Recently I have pushed https://github.com/aperezdc/revolt/commit/a12dbd565005e229adef8571cb396e87bca0fd00 which uses the [gtk.show_uri_on_window()](https://developer.gnome.org/gtk3/stable/gtk3-Filesystem-utilities.html#gtk-show-uri-on-window) function. That function receives as the first parameter the window for which the an URI is opened, and it should take care itself of always opening any needed popups *over* the window.

Could you try updating to a version that includes the above fix? It seems to be working fine for me here. Hint: Using `flatpak update [--user]` will do if you are using the Flatpak.

**Comment by jaragunde** [comment]
The issue is fixed now. Thanks!

**Comment by aperezdc** [comment]
@jaragunde: Great, thanks for confirming!
