### ISSUE TITLE
Notifications don't seem to work under XFCE

### ISSUE THREAD

**Issue by aperezdc** [aperezdc/revolt#6]
According to @clopez, notifications are not working under XFCE, which uses `xfce4-notifyd` as notification daemon.

One possible workaround could be to fall-back to using `libnotify` when under XFCE, or letting the WebKitGTK+ notifications go through instead of converting them to a `GioNotification`.

**Comment by aperezdc** [comment]
I have verified that the notifications indeed do work under [i3](http://i3wm.org/) while using [dunst](http://www.knopwob.org/dunst/) as notification daemon. Which probably points to some issue in the XFCE notification daemon. I will check under XFCE later.

**Comment by aperezdc** [comment]
(@clopez comments.)

I think XFCE don't supports persistent notifications.

The way to have something similar to persistent notifications on XFCE is jut a blinkin icon on the notification area (http://docs.xfce.org/xfce/xfce4-panel/systray)

**Comment by aperezdc** [comment]
Now that #10 was merged, we have support to show status icon in desktops which have a legacy “systray”, for example it shows like this in [Budgie](https://github.com/budgie-desktop/budgie-desktop) (what I have been using to test):

![Status icon in Budgie Desktop](https://cloud.githubusercontent.com/assets/723451/20351452/8b646dde-ac1b-11e6-8eda-994cb2adb592.png)

Can we consider this issue solved and close it?

**Comment by clopez** [comment]
Yes, I think we can close this.
It is working fine for me on XFCE.
