### ISSUE TITLE
Why does the main window have a HeaderBar?

### ISSUE THREAD

**Issue by jplatte** [aperezdc/revolt#66]
It doesn't seem to use the extra space for anything except a loading indicator, which I'd argue would make a lot more sense just being in the middle of the window. This is especially annoying when your window manager doesn't use gtk-themed window headers at all. For example, this is what revolt looks on my usual IM workspace configuration:

![bildschirmfoto vom 2017-07-10 19-19-15](https://user-images.githubusercontent.com/951129/28011187-d4406614-65a4-11e7-8660-e126d856107e.png)

**Comment by aperezdc** [comment]
The header bar is there to follow the GNOME Human Interface Guidelines. I have some plans to add additional controls/information in the header bar; but I have not gotten to do it yet. Even so, I understand the reasoning behind preferring that the window manager decorations (or lack thereof) when using a tiling window manager. I see two possible ways to cater for that preference:

- Adding a CSS class to Revolt's header bar, allowing users of tiling window managers to hide the header bar widget [by tweaking the gtk.css file](https://wiki.archlinux.org/index.php/GTK%2B#Client-side_decorations).
- Adding a option in the application settings to disable usage of the header bar. My personal preference would be to have a hidden setting which can be toggled from the command line using the `gsettings` program or DConf-Editor, but that doesn't show in the preferences window of Revolt.

@jplatte What does sound nicer to you, as an user of a tiling window manager? (I haven't got much of a preference between the two above.)

**Comment by jplatte** [comment]
I didn't know you could overwrite css on a per-user basis. That's pretty cool.

The setting makes more sense in my head, but I'd be fine with either solution

Also, I'm a bit curious about where the GNOME HIG mandate usage of CSD. I don't actually generally dislike GtkHeaderBar, in fact I prefer it when it actually saves space. But I don't see why it would make sense to mandate a big header bar (and thus CSD) when the extra space isn't being used for anything.

**Comment by aperezdc** [comment]
@jplatte As a matter of fact, I had forgotten that we already have a `use-header-bar` setting. You can toggle it with the following command:

```sh
gsettings set \
   org.perezdecastro.Revolt:/org/perezdecastro/Revolt/ \
   use-header-bar false
```

If you use the Flatpak package, you can open a shell session in the same sanboxed environment used by the application with:

```sh
flatpak run --command=/bin/bash org.perezdecastro.Revolt
```

and then use the `gsettings` command above normally.

**Comment by jplatte** [comment]
Oh, okay! Thanks :)
