### ISSUE TITLE
Icon doesn't appear on header bar when application menu is disabled

### ISSUE THREAD

**Issue by jaragunde** [aperezdc/revolt#68]
On a GNOME desktop, you can disable the application menus via e.g. the GNOME Tweak tool (Top Bar -> Show Application Menu -> Off). In that case, the app menu will be made accessible via an icon on the leftmost corner of every window top bar.

If you run Revolt and then disable applications menus, the icon on the top bar appears correctly, but if you boot up Revolt after having disabled that feature, it doesn't.

I'm reproducing this on GNOME 3.24.2.

**Comment by aperezdc** [comment]
I can reproduce this, and it _might_ be related to the change in commit https://github.com/aperezdc/revolt/commit/b852b5474f58f9d8366d21cc63c9750617d3468b but I fail to see why the menu shouldn't appear anyway. I wonder whether this could be an issue in GTK+. Other than using `menus-appmenu-ui` there's nothing else special that Revolt is doing... Or it could be that GTK+ expects also a `menus-traditional.ui` to be present.

At any rate, I would need to investigate this a bit to figure out how to solve it.

**Comment by aperezdc** [comment]
It seems that somehow the menu icon won't show in a GNOME Flashback session as well. Probably the underlying reason is the same.

**Comment by jaragunde** [comment]
This seems to be fixed now.

**Comment by aperezdc** [comment]
@jaragunde: Thanks for commenting. Closing!
