### ISSUE TITLE
Importing E2E keys results in “Your browser does not support the required cryptography extensions”

### ISSUE THREAD

**Issue by axelsimon** [aperezdc/revolt#70]
Hello,
Just installed Revolt and went to import end-to-end encryption (E2E) room keys in Riot's settings.
This doesn't work, throwing the following error:
> Your browser does not support the required cryptography extensions

Any ideas?
Thanks.

**Comment by aperezdc** [comment]
This is a known issue (see #53) caused by the missing WebCrypto implementation in WebKitGTK+, which Revolt uses. Upstream is progressing nicely in this regard, so hopefully soon it will start working.
