### ISSUE TITLE
[query] How can I stop flatpak-installed Revolt from the command line?

### ISSUE THREAD

**Issue by kwill** [aperezdc/revolt#71]
**User story:** I am a software developer scripting my desktop environment. I have installed Revolt using flatpak. I want to close Revolt (if it is open) from a script, so that I can invoke this action along with others in a single script.

`ps -e | grep revolt` doesn't find anything and `killall revolt` returns `no process found`. Searching the GNOME System Monitor GUI for "revolt" returns three process: 2 x bwrap, 1 x python3. Flatpak itself does not appear to have a "stop" command.

**Comment by axelsimon** [comment]
Have you tried pgrep?

> [axel@fedora25:~] $ pgrep -af revolt
8142 bwrap --args 15 revolt
8158 bwrap --args 15 revolt
8159 python3 /app/bin/revolt

I know nothing of the `bwrap` command, but maybe it has an option to achieve what you want.

**Comment by aperezdc** [comment]
@kwill: The cleanest way would be to send a D-Bus message to remotely invoke the `app.quit` action. From the shell (or a script) you can do that with the `gdbus` command:

```sh
gdbus call --session \
  --dest org.perezdecastro.Revolt \
  --object-path /org/perezdecastro/Revolt \
  --method org.gtk.Actions.Activate \
  quit '[]' '{}'
```

The `bwrap` command is used behind the scenes by Flatpak to configure the application sandbox. You don't need to worry about it: it will exit automatically when Revolt exits.

**Comment by kwill** [comment]
That worked exactly as you described. Thanks very much.

**Comment by aperezdc** [comment]
@kwill You're welcome, and thanks for using Revolt :wink:
