### ISSUE TITLE
Package with v0.11.4

### ISSUE THREAD

**Issue by MightyCreak** [aperezdc/revolt#74]
Revolt is still packaged on an old version of Riot (can't get the version number), but it's definitely not the last one.

Also, it makes a long time Revolt hasn't been updated... Is it still maintained?

**Comment by aperezdc** [comment]
Currently Riot is _not_ bundled with Revolt, at least not until #13 is solved. It will just use whichever version of Riot you configure the URL for in the application settings.

And yes, I am still using Revolt everyday, and I will keep maintaining it — I just had not spare time that I could devote to it lately, sorry!
