### ISSUE TITLE
Support independent Revolt instances

### ISSUE THREAD

**Issue by kwill** [aperezdc/revolt#83]
**User story:** I am an everyday user. I want multiple Matrix accounts, so I can separate work and personal contacts/rooms/etc.

**Suggested solution:** In lieu of Riot itself supporting multiple accounts, I'd like to launch a second instance of Revolt in the current desktop session, such that:

* I can start and stop the second instance independently
* it does not share settings with the original instance
* it stores its own settings in a distinct location
* it is treated as a distinct window when alt-tabbing
* (ideally) it has a distinct icon

This has the added benefit of being able to completely close off accounts that I don't want to attend to right now.

Apparently this should be possible with:

    flatpak run org.perezdecastro.Revolt --setting=org.the.new.name --own-name=org.the.new.name

Where:

* `--setting` would be a new Revolt parameter. This would be used to run Revolt as a different dbus name, and also (somehow) define a new data location
* `--own-name` is an existing Flatpak parameter that allows the name to be owned
* ...perhaps these could be merged?

From https://github.com/flatpak/flatpak/issues/1170:

> To run multiple instances you need revolt itself to be able to run as a different dbus name, and that is a request you have to take up with revolt developers.
>
> Once you have that you need to also call it with flatpak run --own-name=org.the.new.name to allow that name to be owned.
>
> For the storage settings there is no current way to automatically do this from flatpak itself, but I guess it could be added by using a separate dir for ~/.var/app/$id

**Comment by aperezdc** [comment]
This shouldn't be too difficult to achieve. Revolt is already using [Gtk.Application](https://developer.gnome.org/gtk3/stable/GtkApplication.html), so if we change the code to let it parse the command line _and_ set the flag to allow changing the application identifier at runtime (that is `G_APPLICATION_CAN_OVERRIDE_APP_ID`), then it will be possible to pass `--gapplication-app-id=<ID>`. Most of the code that needs the application identifier (if not all) already uses `Gtk.Application.get_application_id()` so I expect this won't be a lot of work to implement.

**Comment by aperezdc** [comment]
Funny story: I just checked the code and there is support for overriding the application identifier already there! It is done with the `REVOLT_OVERRIDE_APPLICATION_ID` environment variable:

```sh
REVOLT_OVERRIDE_APPLICATION_ID=org.myself.OtherRevolt revolt
```

or, if you are using Flatpak:

``sh
flatpak run \
    --env=REVOLT_OVERRIDE_APPLICATION_ID=org.myself.OtherRevolt \
    org.perezdecastro.Revolt
```

I hope this helps. If you find any issues using `REVOLT_OVERRIDE_APPLICATION_ID`, please comment here.

**Comment by kwill** [comment]
It works! Thanks.

**Comment by aperezdc** [comment]
@kwill: Great, thanks for confirming that it works for you and closing the issue!
