### ISSUE TITLE
Error resolving “riot.im”: Temporary failure in name resolution

### ISSUE THREAD

**Issue by kwill** [aperezdc/revolt#84]
Steps to reproduce:

* Start Revolt
* In Preferences, confirm Riot URL set to `https://riot.im/app`

What should happen:

* Existing account page is loaded

What happens instead:

* Error message appears (Error resolving “riot.im”: Temporary failure in name resolution)
* Error repeated in the console tab with address

Notes:

* Visiting `https://riot.im/app` in a browser works

**Comment by aperezdc** [comment]
I haven't seen this myself, and cannot reproduce it locally. Did it work again after reloading (right click on the app → “Reload”), or after reopening Revolt?

If you still have this issue, it would be helpful to know which version of Flatpak you are using (`flatpak --version` in a terminal will print the version), and what you were doing when this happened. In particular, the following are interesting:

* Did your computer resume operation from suspend-to-RAM or hibernation?
* Did the network settings change somehow?
  - If you were on Wi-Fi, were you connected to a network which has multiple access points for the same network (SSID)?

**Comment by kwill** [comment]
I'm currently using Flatpak 0.10.3, I'm not sure what version I was on at the time.

I haven't experienced this issue for a while, so either it resolved itself or it's caused by one of the triggers you listed. I'll close the ticket for now, and it can be reopened or referenced if someone with the same error message finds it.
