### ISSUE TITLE
App menu and keyboard shortcuts disabled

### ISSUE THREAD

**Issue by philn** [aperezdc/revolt#87]
This seems to be an issue with the Flatpak version of Revolt. The app menu is greyed out and keyboard shortcuts don't work at all.

Uninstalled (`make run`) version works as expected.
Other Flatpak apps work as expected, I tried the PiTiVi app.

**Comment by philn** [comment]
Maybe this is relevant?

```
Feb 12 09:16:06 ecto-1 systemd[14005]: Started flatpak document portal service.
Feb 12 09:16:06 ecto-1 systemd[14005]: flatpak-com.igalia.Revolt-15876.scope: Failed to add PIDs to scope's control group: Permission denied
Feb 12 09:16:06 ecto-1 systemd[14005]: flatpak-com.igalia.Revolt-15876.scope: Failed with result 'resources'.
Feb 12 09:16:06 ecto-1 systemd[14005]: Failed to start flatpak-com.igalia.Revolt-15876.scope.
```

**Comment by aperezdc** [comment]
I have been able of reproducing this issue after upgrading to Flatpak 0.10.3 myself. For the moment I do not have a proper fix for the menu, but as a stopgap measure I have pushed commit https://github.com/aperezdc/revolt/commit/61646b20f5136dd43c8a77a34ef6624acb53e077, which adds options in the contextual menu to open the preferences window. Having the context menu tweaked is something I had been thinking about before, so it's anyway a small improvement which would be done anyway :wink:

**Comment by aperezdc** [comment]
@philn: Both myself and @jaragunde have the menu entries working fine after commit https://github.com/aperezdc/revolt/commit/61646b20f5136dd43c8a77a34ef6624acb53e077 so if you could please confirm that they are working for you, we can close this issue. Thanks!

**Comment by philn** [comment]
Yes it works now, good job!

**Comment by aperezdc** [comment]
@philn: Great, thanks for confirming and closing the issue :+1:
