### ISSUE TITLE
Allow users to select a custom Riot instance

### ISSUE THREAD

**Issue by knotteye00** [aperezdc/revolt#97]
I run my own riot instance to pair with my matrix server, and I would like to be able to pass a custom riot URL to revolt without editing gschema and recompiling. Would a config file or an argument at runtime (eg `flatpak run org.perezdecastro.Revolt https://custom.riot.instance`) be possible?

**Comment by knotteye00** [comment]
Didn't see the preferences section earlier. Feel like an idiot lmao.

**Comment by aperezdc** [comment]
@knotteye00 Glad you found the option, even before I had the chance to drop by and mention the Preferences panel :smile:

**Comment by glitchphan** [comment]
I came here with the same question. Unfortunately, I don't see a preferences panel, just a login screen. It's probably my desktop UI hiding it, or something.

**Comment by aperezdc** [comment]
@glitchphan Could you try tapping `Ctrl-E` on your keyboard? I think it has gotten harder to reach the preferences window since GNOME started hiding application menus, so I have filed #102 to look into adding some kind of menu in to the header bar that the desktop environment won't swallow.

**Comment by glitchphan** [comment]
Ctrl-e/Ctrl-E does nothing, unfortunately. To top it off, I'm using a distro with its own additions to the UI, ZorinOS. Thanks for the response!
